### ISSUE TITLE
Windows path support

### ISSUE THREAD

**Issue by LordZane** [31i73/atom-dbg-gdb#1]
I have gdb from MSYS2 but i get the following error
`C:UserszaneDropboxc++hello_world.exe: No such file or directory.`

where the path is `C:\Users\zane\dropbox\c++\hello_world.exe`

**Comment by ProPuke** [comment]
Ahh sorry about that.
I've patched filepath handling. Can you let me know if it works okay now?

**Comment by LordZane** [comment]
Thanks! works fine (well I get no errors, ive never used a debugger before so trying to figure out how to actually use this right now xD)
