### ISSUE TITLE
Environment variables for debug target

### ISSUE THREAD

**Issue by xHasKx** [31i73/atom-dbg-gdb#10]
This will be very nice if you could add setting custom environment variables for debug target (executable).
They can be set for gdb process, or maybe gdb has some mi-command for that.
About UI: I propose to use simple text field where I can put JSON (or key=value pairs) with environment variables.

**Comment by xHasKx** [comment]
I can even help with pull request with described implementation

**Comment by ProPuke** [comment]
This is now achievable using the `env_vars` option in your debug config file (See [supported options](/31i73/atom-dbg-gdb/blob/master/README.md#supported-options))
