### ISSUE TITLE
No console input to debuggee application

### ISSUE THREAD

**Issue by cspk** [31i73/atom-dbg-gdb#13]
When I debug an application that contains some input function calls like `scanf`, there is no way to input data through the console, it just stops like this:
![bug](https://cloud.githubusercontent.com/assets/6134003/22629388/b029330e-ec06-11e6-9c88-f3ded26ca07a.png)
After that, the only available debug action is to stop the debugging session.

**Comment by cspk** [comment]
And as you see, there's no output either, all the output appears in the console only when the process finishes, not as the debugging steps go through.

**Comment by DatBewar** [comment]
It's would be nice to have it, it's a very great plugin !

**Comment by vanossj** [comment]
I'm working on this, no eta yet.

**Comment by ProPuke** [comment]
@vanossj Greatly appreciated again on this.

To save you time it might make sense to not extend the `atom-output` package for this, but just use another terminal package if there's one that already does this.

`atom-dbg` doesn't need to use `atom-output`. I only did so as I was already using `atom-output` with some custom packages of my own, which it had been written for.

**Comment by alexanderzhirov** [comment]
Data entry does not work, the input console does not appear. All packages are installed.

![image](https://user-images.githubusercontent.com/37277056/111537213-3633f000-877c-11eb-9631-70efff300c4b.png)
![2021-03-17_23-52](https://user-images.githubusercontent.com/37277056/111537045-0a186f00-877c-11eb-9e9a-da8acb3b34d4.png)
