### ISSUE TITLE
Debugger crashes immediately with A syntax error in expression, near `new-console on'

### ISSUE THREAD

**Issue by DerGenaue** [31i73/atom-dbg-gdb#22]
Latest Version,
Linux mint.

As I've found out, this command is only available on windows.
I don't know why the else branch (main.coffe @272) even triggers

**Comment by DerGenaue** [comment]
Thx

**Comment by ProPuke** [comment]
Thanks, should be okay now!

The else condition triggers if [output-panel](https://atom.io/packages/output-panel) isn't installed, or you're on windows and `output-panel` doesn't support interactive tty sessions (the later is why it was attempting to create a new console, instead).

Seems there was also a bug with `output-panel` on linux, causing it to annoyingly pop up with a shell every time. I've fixed that now.

`dbg-gdb` should work with or without `output-panel` installed, now.
