### ISSUE TITLE
Pretty printers not used in the variables tree

### ISSUE THREAD

**Issue by BenjaminNavarro** [31i73/atom-dbg-gdb#26]
When a pretty printer is defined for a type, it is used to display the variable's tooltip but not when navigating the tree.

Exemple: 
![bug_dbg-gdb](https://user-images.githubusercontent.com/14923636/32547458-b51785b4-c482-11e7-839c-46d8dc81a051.png)

With gdb I have what I expect:
```
(gdb) p force_sensor
$1 = kbot::pro_ptr<kbot::ForceSensor> = {
  name = "force_sensor",
  data = uninitialized
}
```

Is this possible to fix?

**Comment by ProPuke** [comment]
Yep, I'm looking into doing so now and tidying this up. Cheers for the prompt.
