### ISSUE TITLE
Resizable panel

### ISSUE THREAD

**Issue by janosimas** [31i73/atom-dbg-gdb#3]
The variables panel is small for some variables, can't it be resizable?
And detachable from the stack?

**Comment by ProPuke** [comment]
This is technically a https://github.com/31i73/atom-dbg issue. dbg-gdb is just the backend. dbg is the graphical frontend :]

Yeah, it just hasn't happened yet. It does need horizontal (and vertical, for stack vs variables) sizing.

By detachable do you mean as a floating window (not sure if this is something we can do with atom), or as the ability to split the variables panel so it's *next* to the stack, with both at full height?

**Comment by janosimas** [comment]
I meant splitting, as an atom tab.
It could start as a vertical split but draggable, so could be _next_ to the stack, with both at full height.

**Comment by ProPuke** [comment]
This has now been added for the new Atom 1.17 beta (https://github.com/31i73/atom-dbg/commit/ec99a8b766a6a1bbc0ed9e6a6cf2357aebf8987f)

They can be docked to the side of the window, split, resized, dragged around, grouped as tabs (and anything else you can do with regular TextEditors in the Workspace)
