### ISSUE TITLE
Startup Script

### ISSUE THREAD

**Issue by davidrohr** [31i73/atom-dbg-gdb#34]
I usually have a startup script for my application, which sets some environment variables, and perhaps does some cleanup in the working directory.
I cannot put that script as executable, since gdb could only debug bash than.
It would be nice if the configuration dialog (or the config file) could offer an option for a script to execute before starting the actual gdb session.

**Comment by ceremcem** [comment]
When do you need to run your `cleanup_script`? If it was right before starting the debugger, you can use [`gdbinit`](https://github.com/31i73/atom-dbg-gdb/issues/29#issuecomment-351900424).

**Comment by davidrohr** [comment]
Indeed, thanks for the idea.
