### ISSUE TITLE
gdb commands

### ISSUE THREAD

**Issue by davidrohr** [31i73/atom-dbg-gdb#35]
I might be stupid, but I could not figure out how to issue console commands to the debugger in the output panel. Is this possible at all?

This would be extremely helpful, in particular, if it would stay in sync with atom, i.e., issues "next" command should be identical than pressing step over button.

**Comment by JustBeefalo** [comment]
I find it very annoying to deal with pointers. e.g. while I can see the first value of a buffer in the variables pane I can't print the entire contents. Being able to do a simple `p *buf@len` would help immeasurably.

Maybe that specific example has a better solution, but I find it hard to use gdb without access to console commands.
