### ISSUE TITLE
Variables information

### ISSUE THREAD

**Issue by janosimas** [31i73/atom-dbg-gdb#4]
The variables panel doesn't show the variable type and some of them are not readable.
Could pointers and smart pointers show the content?
Maybe include debug helpers path in the config?

**Comment by janosimas** [comment]
Can I be of some assistance?

**Comment by ProPuke** [comment]
## dbg:

Variable types were originally shown, but I decided to hide them to simplify the view (as the name and value seemed a lot more important when debugging at runtime). The fact that you can't size the panels horizontally yet to allow more room was probably also a factor.

How about if there was a toggle button on the variables panel titlebar for showing/hiding types? 

## dbg-gdb:

It seems like dbg-gdb should probably come with common helpers for C++ and other common languages, yeah. I've not looked into this yet (I tend to actually use lldb in the wild, but its mi support had a few issues, so I've ended up back with gdb for now).

Config path(s) for custom helpers sounds like a good idea :]

Any assistance would be appreciated, all pr's graciously received. If it's not a code change, but just some helpers then feel free to commit them into a directory and I'll add in the code to to connect them. Cheers.

**Comment by janosimas** [comment]
# Types
Maybe tip for variables types? Only when mouse over?
I like the clean view but types are important for debugging...
