### ISSUE TITLE
This file cannot be debugged

### ISSUE THREAD

**Issue by SimoneFerrari99** [31i73/atom-dbg-gdb#44]
Help please! 

![image](https://user-images.githubusercontent.com/49599798/56086302-78e44380-5e54-11e9-87d6-1bbc1c7232d9.png)

**Comment by arun13** [comment]
I am also facing the same issue for c++ file debugging. Kindly help.

**Comment by Moenish** [comment]
Same problem here...

**Comment by Moenish** [comment]
@Scheggia99 What kind of file are you trying to debug?

**Comment by SimoneFerrari99** [comment]
file .c

Il dom 23 feb 2020, 00:03 Moenish <notifications@github.com> ha scritto:

**Comment by Moenish** [comment]
Won't work with .c files, you have to compile it first into an executable, .exe file. Then you can debug that.

**Comment by SimoneFerrari99** [comment]
[image: image.png]
gcc Es.c -o Es


Il giorno lun 24 feb 2020 alle ore 14:55 Moenish <notifications@github.com>
ha scritto:
