### ISSUE TITLE
stderr not displayed

### ISSUE THREAD

**Issue by janosimas** [31i73/atom-dbg-gdb#5]
When I run a process the output panel shows the creation and destruction of threads but not the stdout or the stderr.

Could it have tabs?
stdout, stderr, threads...

**Comment by ProPuke** [comment]
What OS are you testing in?

How are your printing to stdout? Is output being flushed?

Tabs are something I'm thinking on..

**Comment by janosimas** [comment]
I'm using linux ubuntu 14.04

I did some test here and I was not using stdout, I used [clog](http://en.cppreference.com/w/cpp/io/clog)
stdout is working fine.
stderr isn't showing either.

**Comment by ProPuke** [comment]
Cheers I'll get that sorted.

Tabs will probably come later, as I wanna work out the best way of doing that for the future. So stdout and stderr will appear together for now.

Note that clog won't appear in the output until it's flushes, due to output buffering.
