### ISSUE TITLE
Parameters to program execution

### ISSUE THREAD

**Issue by janosimas** [31i73/atom-dbg-gdb#6]
Maybe another item in the context menu to add parameters to the execution.

(hope you don't mind all these issues :-) )

**Comment by janosimas** [comment]
Another solution, even better, would be allow to create a list of targets for the debugger.

**Comment by vanossj** [comment]
some level of configuration would be great. I usually find myself debugging dynamic libraries, the current 'debug this file' doesn't allow for that.

Maybe the front end could have a generic 'debug ...' command that opens a panel to input args and choose from installed debug backends.
